version: v1
name: ""
deps:
  - buf.build/googleapis/googleapis
build:
  excludes: []
lint:
  use:
    - STANDARD
  except:
    - PACKAGE_DEFINED
    - PACKAGE_VERSION_SUFFIX
    - PACKAGE_DIRECTORY_MATCH
    - RPC_REQUEST_STANDARD_NAME
    - RPC_REQUEST_RESPONSE_UNIQUE
    - RPC_RESPONSE_STANDARD_NAME
    - SERVICE_SUFFIX
  ignore: []
  allow_comment_ignores: false
  enum_zero_value_suffix: _UNDEFINED
  rpc_allow_same_request_response: false
  rpc_allow_google_protobuf_empty_requests: false
  rpc_allow_google_protobuf_empty_responses: false
  service_suffix: Service
breaking:
  use:
    - FILE
  except: []
  ignore: []
  ignore_only: {}
  ignore_unstable_packages: false
